### ISSUE TITLE
How to Dial with timeout?

### ISSUE THREAD

**Issue by ghost** [wzshiming/socks4#1]

**Comment by kenegdane** [comment]
> This can be done with `context.WithTimeout`
> 
> ```go
> 	dialer, _ := socks4.NewDialer("socks4://xxxx")
> 	ctx := context.WithTimeout(context.Background(), 1*time.Second)
> 	dialer.DialContext(ctx, "tcp", "xxx")
> ```

Can i use this instead?
```go
dialer, err := socks4.NewDialer("socks4://" + _PROXY)
	if err != nil {
		return
	}
	dialer.Timeout = 5 * time.Second
	conn, err = dialer.Dial("tcp", _HOST + ":" + _PORT)
```

**Comment by wzshiming** [comment]
Of course, but recommends using `context.Context` in Golang
